version: "3"
services:
  app:
    build: ./app
  # 開発用DB
  postgres-service:
    build: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: crawler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  # テスト用DB
  db_test:
    build: ./postgres
    ports:
      - 4321:5432
    environment:
      POSTGRES_DB: crawler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
